apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lizk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lizk
    app.kubernetes.io/part-of: tkrw-pr712-0075-0055-app
  name: devfile-sample-lizk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lizk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lizk
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-lizk@sha256:f5ed545ff484b19dadcc3372d3a031fbd379d1e0e7272f0be8659dca1107826e
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
